export { boolCodec } from "./Bool";
export { boolArrayCodec } from "./BoolArray";
export { bool64bitKeyCodec } from "./Bool64bitKey";
export { intCodec } from "./Int";
export { uintCodec } from "./UInt";
export { uintCodec as enumCodec } from "./UInt";
export { uintArrayCodec as enumArrayCodec } from "./UIntArray";
export { floatCodec } from "./Float";
export { int64Codec } from "./Int64";
export { uint64Codec } from "./UInt64";
export { intArrayCodec } from "./IntArray";
export { uintArrayCodec } from "./UIntArray";
export { floatArrayCodec } from "./FloatArray";
export { int64ArrayCodec } from "./Int64Array";
export { uint64ArrayCodec } from "./UInt64Array";
export { vector2Codec } from "./Vector2";
export { vector2ArrayCodec } from "./Vector2Array";
export { vector3Codec } from "./Vector3";
export { vector3ArrayCodec } from "./Vector3Array";
export { wString16Codec } from "./WString16";
export { wString16ArrayCodec } from "./WString16Array";
export { wString32Codec } from "./WString32";
export { wString32ArrayCodec } from "./WString32Array";
export { wString64Codec } from "./WString64";
export { wString64ArrayCodec } from "./WString64Array";
export { binaryCodec } from "./Binary";
export { binaryArrayCodec } from "./BinaryArray";
export { string16Codec } from "./String16";
export { string16ArrayCodec } from "./String16Array";
export { string32Codec } from "./String32";
export { string32ArrayCodec } from "./String32Array";
export { string64Codec } from "./String64";
export { string64ArrayCodec } from "./String64Array";
import { StructCodec, ScalarStructType, ArrayStructType } from "../Types";
export declare const scalarCodecs: Partial<Record<ScalarStructType, StructCodec<unknown>>>;
export declare const arrayCodecs: Partial<Record<ArrayStructType, StructCodec<unknown>>>;
